# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  # Enable bcachefs support in the kernel
  boot.supportedFilesystems = [ "bcachefs" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.kernelPackages = pkgs.linuxPackages_latest;  # bcachefs needs recent kernel
  
  boot.initrd.availableKernelModules = [ "xhci_pci" "ehci_pci" "ahci" "usbhid" "uas" "sd_mod" "bcachefs" ];
  boot.initrd.kernelModules = [ "bcachefs" ];
  boot.extraModulePackages = [ ];

  fileSystems = {
    "/boot" = {
      device = "/dev/disk/by-label/boot";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

    "/" = {
      device = "/dev/disk/by-label/bcache-pool";
      fsType = "bcachefs";
      options = [ 
        "compression=zstd"
        "metadata_replicas=2"
        "data_replicas=2"
      ];
    };

    "/var/lib/postgresql" = {
      device = "/dev/disk/by-label/bcache-pool";
      fsType = "bcachefs";
      options = [
        "subvol=postgresql"
        "compression=zstd"
      ];
    };

    "/var/lib/neon" = {
      device = "/dev/disk/by-label/bcache-pool";
      fsType = "bcachefs";
      options = [
        "subvol=neon"
        "compression=zstd"
      ];
    };

    "/var/lib/couchdb" = {
      device = "/dev/disk/by-label/bcache-pool";
      fsType = "bcachefs";
      options = [
        "subvol=couchdb"
        "compression=zstd"
      ];
    };
  };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}