name: "Test"
on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: cachix/install-nix-action@v25
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
        extra_nix_config: |
          experimental-features = nix-command flakes

    - name: Check flake
      run: |
        nix flake check

    - name: Build system configurations
      run: |
        nix build .#nixosConfigurations.*.system
        nix build .#homeConfigurations.*.activationPackage
        
    - name: Check evaluation
      run: |
        nix eval .#nixosConfigurations
        nix eval .#homeConfigurations